# Generated by Django 5.1.1 on 2024-10-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryHello', '0004_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
