# Generated by Django 5.1.2 on 2024-10-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryHello', '0006_testtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
