# Generated by Django 5.1.2 on 2024-10-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryHello', '0007_remove_enrollment_course_remove_enrollment_student_and_more'),
    ]



