# Generated by Django 5.1.2 on 2024-10-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryHello', '0008_delete_testtable'),
    ]


