# Generated by Django 5.1.2 on 2024-10-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryHello', '0009_delete_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
