# Generated by Django 5.1.2 on 2024-10-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testtable',
            table=None,
        ),
    ]
