# Generated by Django 5.1.2 on 2024-10-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0004_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
